"""The literal text of every generated artifact. No logic beyond substitution.

Nothing here interpolates unvalidated input: `naming.validate_*` has already refused
anything containing a newline, a space, `%`, `}` or a quote, so these templates never
need to escape and never can be broken out of.
"""

from __future__ import annotations

# Directives shared by both units. Together these keep `systemd-analyze security`
# under 4.0; removing any one of them raises the exposure score.
#
# `IPAddressDeny=any` with `IPAddressAllow=localhost` is the one that does not just
# raise a score: it is what makes the app unreachable from the internet even when the
# app binds `0.0.0.0`. `SocketBindAllow=` restricts the port, not the address, so
# without this an app that ignores `--bind 127.0.0.1` would answer around Caddy and
# around the owner cookie. Both units therefore only ever speak to loopback.
HARDENING = """\
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
PrivateUsers=yes
PrivateMounts=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
ProcSubset=pid
RestrictSUIDSGID=yes
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
IPAddressDeny=any
IPAddressAllow=localhost
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources
SystemCallArchitectures=native
CapabilityBoundingSet=
AmbientCapabilities=
DevicePolicy=closed
RemoveIPC=yes
UMask=0077
"""

APP_UNIT = """\
[Unit]
Description=smallapp {name} ({kind})
Documentation=https://github.com/jakerothstein/smallapp-unit
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={user}
Group={user}
WorkingDirectory={app_dir}
Environment=PORT={port}
Environment=HOME=/var/lib/smallapp/{name}
Environment=UV_CACHE_DIR=/var/lib/smallapp/{name}/uv-cache
ExecStart={exec_start}
Restart=always
RestartSec=1
StateDirectory=smallapp/{name}
MemoryMax={memory_max}
TasksMax=64
SocketBindAllow=tcp:{port}
SocketBindDeny=any
{hardening}
[Install]
WantedBy=multi-user.target
"""

GW_UNIT = """\
[Unit]
Description=smallapp {name} auth gateway
Documentation=https://github.com/jakerothstein/smallapp-unit
After=network-online.target smallapp-{name}.service
Wants=network-online.target

[Service]
Type=simple
User={gw_user}
Group={gw_user}
WorkingDirectory=/var/lib/smallapp/{name}-gw
Environment=HOME=/var/lib/smallapp/{name}-gw
EnvironmentFile={env_path}
ExecStart={gw_exec_start}
Restart=always
RestartSec=1
StateDirectory=smallapp/{name}-gw
MemoryMax={gw_memory_max}
TasksMax=32
SocketBindAllow=tcp:{gw_port}
SocketBindDeny=any
{hardening}
[Install]
WantedBy=multi-user.target
"""

ENV_FILE = """\
# Generated by smallapp for unit {name}. Mode 0600, root-owned. Do not commit.
SMALLAPP_SECRET={secret}
SMALLAPP_TOKEN_HASH={token_hash}
SMALLAPP_GW_PORT={gw_port}
SMALLAPP_UPSTREAM=127.0.0.1:{port}
PORT={port}
"""

VHOST_HEAD = """\
# Generated by smallapp for unit {name}. Edit smallapp inputs, not this file.
{domain} {{
{tls_line}\
    handle /_smallapp/* {{
        reverse_proxy 127.0.0.1:{gw_port}
    }}

    forward_auth 127.0.0.1:{gw_port} {{
        uri /_smallapp/auth
        copy_headers X-Smallapp-User
    }}

"""

VHOST_PROXY_TAIL = """\
    reverse_proxy 127.0.0.1:{port}
}}
"""

VHOST_STATIC_TAIL = """\
    root * {app_dir}
    file_server
}}
"""

TLS_INTERNAL = "    tls internal\n\n"
